src/app/config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/new'
  get 'static_pages/create'

  get '/about', to:'static_pages#about' 

  resources :contact, only: [:index, :new, :create]

  root to: "welcome#index"

  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'
  get '/users', to: 'users#new'

  get 'favorite_colleges', to: 'favorite_colleges#show'
  get 'favorite_spotteds', to: 'favorite_spotteds#show'
  get 'list_likes', to: 'spotteds#list_likes'
  post 'setting_manager', to: 'administrators#setting_manager'

  get 'per_area', to: 'colleges#per_area'

  resources :users, only: [:new, :create, :show, :edit, :update]
  
  resource :users do
    member do
      post :change_menu_preference
    end
  end

  resources :colleges, only: [:new, :create, :show, :index, :edit, :update] do
    resources :spotteds, only: [:new, :create, :show, :index, :destroy]
    resources :administrators, only: [:show, :destroy]
  end

  resources :colleges, only: [:new, :create, :show, :index, :edit, :update] do
    resources :college_whitelists
  end

  resources :colleges do
    put :favorite, on: :member
  end

  resources :spotteds, only: [:new, :create, :show, :index, :delete] do
    resources :comments
  end

  resources :colleges, only: [:new, :create, :show, :index, :edit, :update] do
    resources :college_whitelists, only: [:new, :create, :index, :update]
    get 'verify_permission', to: 'college_whitelists#verify_permission'
  end
  
  resources :spotteds, only: [:new, :create, :show, :index] do
    resources :likes
  end

  resources :spotteds do
    put :favorite, on: :member
  end

end

src/app/app/models/administrator.rb
class Administrator < ApplicationRecord
    belongs_to :user
    belongs_to :college
end

src/app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/app/app/models/college.rb
class College < ApplicationRecord
    VALID_HEX_COLOR = /\A#?(?:[A-F0-9]{3}){1,2}\z/i

    validates :name, presence:true, length: { maximum:65 }
    validates :initials, length: { maximum:8 }
    validates :city, presence:true, length: { maximum:30 }
    validates :state, presence:true, length: { maximum:2 }
    validates :country, presence:true, length: { maximum:30 }
    validates :unit, length: { maximum:20 }
    validates :background_color, format: { with: VALID_HEX_COLOR }, :allow_nil => true
    validates :font_family, length: { maximum: 30 }
    validates :background_image, url: {no_local: true, allow_blank: true}
    validates :font_color, format: { with: VALID_HEX_COLOR }, :allow_nil => true
    validates :request_to_participate, presence: false
    validates :admin_approves_spotted, presence: false

    belongs_to :user

    has_many :spotteds, dependent: :destroy
    has_many :favorite_colleges, dependent: :destroy
    has_many :favorited_by, through: :favorite_colleges, source: :user, dependent: :destroy
    has_many :administrator
    has_many :college_whitelist
  
end

src/app/app/models/college_whitelist.rb
class CollegeWhitelist < ApplicationRecord
    validates :status, presence: true
    enum status: {pending: 0, approved: 1, rejected: 2}

    belongs_to :user
    belongs_to :college
end

src/app/app/models/comment.rb
class Comment < ApplicationRecord

    validates :content, presence: true, length: {minimum: 1}

    belongs_to :spotted
    belongs_to :user
end

src/app/app/models/contact.rb
class Contact < MailForm::Base
    attribute :name,      :validate => true
    attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :message
  
    # Declare the e-mail headers. It accepts anything the mail method
    # in ActionMailer accepts.
    def headers
      {
        :subject => "Contact Form Inquiry",
        :to => "spottappteam@gmail.com",
        :from => %("#{name}" <#{email}>)
      }
    end
  end

src/app/app/models/favorite_college.rb
class FavoriteCollege < ApplicationRecord
    belongs_to :college
    belongs_to :user
end

src/app/app/models/favorite_spotted.rb
class FavoriteSpotted < ApplicationRecord
    belongs_to :spotted
    belongs_to :user
end

src/app/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :spotted
end

src/app/app/models/spotted.rb
class Spotted < ApplicationRecord
    validates :image, presence: false
    validates :content, presence: true, length: {minimum: 1}    

    belongs_to :college
    belongs_to :user
    has_many :like, dependent: :destroy
    has_many :comment, dependent: :destroy
    has_many :favorite_spotteds, dependent: :destroy
    has_many :favorited_by, through: :favorite_spotteds, source: :user, dependent: :destroy
end

src/app/app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

    validates :email, presence: true, length: {maximum: 255}, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: true }
    validates :nickname, presence: true, length: {maximum: 30}, uniqueness: { case_sensitive: true }
    validates :first_name, presence: true, length: {maximum: 50}
    validates :last_name, presence: true, length: {maximum: 50}
    validates :password, presence: true, length: {minimum: 6}
    validates :password_confirmation, presence: true, length: {minimum: 6}
    validates :birth_date, presence: true
    validates :city, presence: true
    validates :state, presence: true, length: {maximum: 2, minimum: 2}
    validates :country, presence: true
    validate :profile_picture_content_type

    has_many :spotted
    has_many :college
    has_many :like, dependent: :destroy
    has_many :comment, dependent: :destroy
    has_many :favorite_colleges
    has_many :favorites, through: :favorite_colleges, source: :college
    has_many :administrator
    has_many :college_whitelist
    has_many :favorite_spotteds
    has_many :notification, through: :favorite_spotteds, source: :spotted

    def profile_picture_content_type
        if self[:profile_picture_content_type]
            unless self[:profile_picture_content_type] == "image/jpeg" || self[:profile_picture_content_type] == "image/png"
                errors.add(:profile_picture_content_type, "deve ser no formato JPEG ou PNG")
            end
        end
    end

end

src/app/app/helpers/application_helper.rb
module ApplicationHelper
end

src/app/app/helpers/colleges_helper.rb
module CollegesHelper
end

src/app/app/helpers/comments_helper.rb
module CommentsHelper
end

src/app/app/helpers/contact_helper.rb
module ContactHelper
end

src/app/app/helpers/likes_helper.rb
module LikesHelper
end

src/app/app/helpers/sessions_helper.rb
module SessionsHelper

    def sign_in(user)
        session[:user_id] = user.id
    end

    def sign_out
        session.delete(:user_id)
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def user_signed_in?
        !current_user.nil?
    end
end

src/app/app/helpers/spotteds_helper.rb
module SpottedsHelper
end

src/app/app/helpers/users_helper.rb
module UsersHelper
end

src/app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

src/app/app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="">
        <div class="alert alert-danger">
            Ops! Encontramos <%= pluralize(object.errors.count, 'erro', 'erros') %>
            <ul>
                <% object.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    </div>
<% end %>

src/app/app/views/layouts/_footer.html.erb
<footer>
    <small>
        <%= link_to 'Spottapp. Todos os direitos reservados.', "#" %>
    </small>

    <nav>
        <ul id="spottapp-static-links">
            <li>
                <%= link_to 'Sobre', about_path %>
            </li>
            <li>
                <%= link_to 'Contato', contact_index_path %>
            </li>
        </ul>
    </nav>
</footer>

src/app/app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" id="spottapp-header">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            
            <div class="big-screen">
                <% if user_signed_in? %>
                    <%= link_to image_tag('spottapp_logo.svg', height: "45"), user_path(current_user), class: 'navbar-brand' %>
                <% else %>
                    <%= link_to image_tag('spottapp_logo.svg', height: "45"), root_url, class: 'navbar-brand' %>
                <% end %>
            </div>

            <div class="small-screen">
                <% if user_signed_in? %>
                    <%= link_to image_tag('spottapp_icon_logo.svg', height: "45"), user_path(current_user), class: 'navbar-brand' %>
                <% else %>
                    <%= link_to image_tag('spottapp_icon_logo.svg', height: "45"), root_url, class: 'navbar-brand' %>
                <% end %>
            </div>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <% if user_signed_in? %>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                    <% if current_user.profile_picture? %>
                        <img src="data:image;base64,<%= current_user.profile_picture %>" class="img-responsive" style="width: 40px; height: 40px; float: left; border-radius: 50px;" alt="Profile picture">
                    <% else %>
                        <%= image_tag 'default_profile_picture.png', alt: 'Profile picture', class: 'img-responsive', style: "width: 40px; height: 40px; float: left;" %>
                    <% end %>   
                    <li class="dropdown">          
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                            aria-expanded="false"><%= current_user.first_name %><span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><%= link_to 'Editar perfil', edit_user_path(@current_user.id), method: :get %></li>
                            <li><%= link_to 'Menu de Faculdades', colleges_path, method: :get %></li>
                            <li><%= link_to 'Menu de Favoritas', favorite_colleges_path, method: :get %></li>
                            <li><%= link_to 'Sair', sair_path, method: :delete %></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle3" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-bell"></i>
                    </a>
                    <ul class="dropdown-menu notify-drop">
                        <div class="notify-drop-title">
                            <div class="row">
                                <div class="col-md-6 col-sm-6 col-xs-6">Notificações</div>
                                <div class="col-md-6 col-sm-6 col-xs-6 text-right"><a href="" class="rIcon allRead" data-tooltip="tooltip" data-placement="bottom" title="tümü okundu."><i class="fa fa-dot-circle-o"></i></a></div>
                            </div>
                        </div>
                    <!-- end notify title -->
                    <!-- notify content -->
                    <% if already_favorited_any_spotted%>
                        <div class="drop-content">
                            <% FavoriteSpotted.where(user_id: current_user.id).each do |fav| %>
                                <% Comment.where(spotted_id: fav.spotted_id).each do |comment| %>
                                    <% if comment.user_id != @current_user.id %>
                                    <li>
                                        <div class="col-md-3 col-sm-3 col-xs-3"><div class="notify-img"><img src="http://placehold.it/45x45" alt=""></div></div>
                                        <div class="col-md-9 col-sm-9 col-xs-9 pd-l0">Novo comentário de <a href=""><%= comment.user.first_name %></a> 
                                        <p>Comentário: <%= comment.content %></p>
                                        <a href="<%= college_spotted_path(comment.spotted.college.id, comment.spotted.id) %>"><p class="time">Novo comentário no spotteds de <%= comment.spotted.college.initials %></p></a>
                                        </div>
                                    </li>
                                    <%end%>
                                <%end%>
                            <%end%>
                        <% end %>
                        </div>
                        <div class="notify-drop-footer text-center"></div>
                    </div>
                    </ul>
                    </li>
                    </ul>
                </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
        <% end %>
    </div><!-- /.container-fluid -->
</nav>

src/app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spottapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag asset_path('favicon.ico') %>
    <link rel="manifest" href="/manifest.json" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <% if content_for? :for_head %>
      <%= yield :for_head %>
    <% end %>
  </head>

  <body>
    <%= render 'layouts/header' %>

		<div class="container" id="content-container">
      
      <% flash.each do |message_type, message| %>
        <%= content_tag 'div', class: "alert alert-#{message_type} alert-dismissible", role: 'alert' do %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= message %>
        <% end %>
      <% end %>

      <%= yield %>

      <%= render 'layouts/footer' %>
		</div>	
  </body>
</html>