src/app/config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/new'
  get 'static_pages/create'

  get '/about', to:'static_pages#about' 

  resources :contact, only: [:index, :new, :create]

  root to: "welcome#index"

  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'
  get '/users', to: 'users#new'

  get 'favorite_colleges', to: 'favorite_colleges#show'
  get 'favorite_spotteds', to: 'favorite_spotteds#show'
  get 'list_likes', to: 'spotteds#list_likes'
  post 'setting_manager', to: 'administrators#setting_manager'

  get 'per_area', to: 'colleges#per_area'

  resources :users, only: [:new, :create, :show, :edit, :update]
  
  resource :users do
    member do
      post :change_menu_preference
    end
  end

  resources :colleges, only: [:new, :create, :show, :index, :edit, :update] do
    resources :spotteds, only: [:new, :create, :show, :index, :destroy]
    resources :administrators, only: [:show, :destroy]
  end

  resources :colleges, only: [:new, :create, :show, :index, :edit, :update] do
    resources :college_whitelists
  end

  resources :colleges do
    put :favorite, on: :member
  end

  resources :spotteds, only: [:new, :create, :show, :index, :delete] do
    resources :comments
  end

  resources :colleges, only: [:new, :create, :show, :index, :edit, :update] do
    resources :college_whitelists, only: [:new, :create, :index, :update]
    get 'verify_permission', to: 'college_whitelists#verify_permission'
  end
  
  resources :spotteds, only: [:new, :create, :show, :index] do
    resources :likes
  end

  resources :spotteds do
    put :favorite, on: :member
  end

end

src/app/app/models/college.rb
class College < ApplicationRecord
    VALID_HEX_COLOR = /\A#?(?:[A-F0-9]{3}){1,2}\z/i

    validates :name, presence:true, length: { maximum:65 }
    validates :initials, length: { maximum:8 }
    validates :city, presence:true, length: { maximum:30 }
    validates :state, presence:true, length: { maximum:2 }
    validates :country, presence:true, length: { maximum:30 }
    validates :unit, length: { maximum:20 }
    validates :background_color, format: { with: VALID_HEX_COLOR }, :allow_nil => true
    validates :font_family, length: { maximum: 30 }
    validates :background_image, url: {no_local: true, allow_blank: true}
    validates :font_color, format: { with: VALID_HEX_COLOR }, :allow_nil => true
    validates :request_to_participate, presence: false
    validates :admin_approves_spotted, presence: false

    belongs_to :user

    has_many :spotteds, dependent: :destroy
    has_many :favorite_colleges, dependent: :destroy
    has_many :favorited_by, through: :favorite_colleges, source: :user, dependent: :destroy
    has_many :administrator
    has_many :college_whitelist
  
end

src/app/app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
    before_action :require_logged_in_user
    before_action :set_college, only: [:edit, :update] 

    def new
        @college = College.new
        @college.user = current_user
    end

    def show
        @college = College.find(params[:id])
    end

    def index
        @colleges = College.all
    end

    def create
        @college = College.new(college_params)
        @college.user = current_user
        if @college.save
            current_user.favorites << @college
            @cw = CollegeWhitelist.new(college: @college, user: current_user, status: "approved")
            if @cw.save
                flash[:sucess] = 'Faculdade cadastrada com sucesso'
                redirect_to root_url
            else
                flash[:danger] = 'Ocorreu um erro com o cadastro'
                render 'new'
            end
        else
            render 'new'
        end
    end

    def favorite
        @college = College.find(params[:id])
        type = params[:type]
        if type == "favorite"
            current_user.favorites << @college
            notice = "Você favoritou #{@college.name}"
            flash[:success] = notice
            redirect_back fallback_location: colleges_path

        elsif type == "unfavorite"
            current_user.favorites.delete(@college)
            notice = "Você desfavoritou #{@college.name}"
            flash[:success] = notice
            redirect_back fallback_location: colleges_path
        
        elsif type == "admin"
            notice = "Você é o administrador de #{@college.name} e não pode desfavoritá-la."
            flash[:danger] = notice
            redirect_back fallback_location: colleges_path

        else
            redirect_back fallback_location: colleges_path, notice: 'Nada aconteceu.'
        end
    end

    def update
        if @college.update(college_params)
            flash[:success] = 'Dados atualizados'
            redirect_to edit_college_path(@college)
        else
            render 'edit'
        end
    end

    def destroy
        @college = College.find(params[:id])
        @college_whitelist = CollegeWhitelist.find_by(college_id: @college.id)
        @college_whitelist.destroy
        @college.destroy
        notice = "A página do(a) #{@college.name} foi deletada."
        flash[:success] = notice
        redirect_to favorite_colleges_path
    end

    def per_area
        state = current_user.state
        city = current_user.city

        if state && city
            @colleges = College.where(state: state).or(College.where(city: city))
        elsif state
            @colleges = College.where(state: state)
        else
            @colleges = College.where(city: city)
        end
    end

    private 
        def college_params
            params.require(:college).permit(:name, :initials, :city, :state, :country, :unit, :user_id, :background_color, :font_family, :background_image, :font_color, :request_to_participate, :admin_approves_spotted)
        end

        def set_college
            @college = College.find(params[:id])
        end
end

src/app/app/helpers/colleges_helper.rb
module CollegesHelper
end

src/app/app/views/colleges/edit.html.erb
<div class="colleges" id="edit">

    <div class="jumbotron">
        <h2 class="title"><%= @college.name %></h2>
        <div class="form">
            <%= form_for @college do |f| %>

                <legend><%= translate 'identidade_visual' %></legend>
                
                <div class="box">
                    <div class="left small">
                        <%= f.label :background_color %>
                        <%= f.color_field :background_color, class: "form-control" %>
                    </div>
                    <div class="right big">
                        <%= f.label :background_image %>
                        <%= f.text_field :background_image, class: "form-control" %>
                    </div>
                </div>

                <div class="box">
                    <div class="left small">
                        <%= f.label :font_color %>
                        <%= f.color_field :font_color, class: "form-control" %>
                    </div>
                    <div class="right big">
                        <%= f.label :font_family %>
                        <%= f.text_field :font_family, class: "form-control" %>
                    </div>
                </div>

                <legend><%= translate 'administracao' %></legend>
                
                <div class="box">
                    <div class="left medium">
                        <%= f.label :request_to_participate %>
                        <%= f.select :request_to_participate, ([['Sim', 1], ['Não', 0]]), {}, { class: "form-control"} %>
                    </div>
                    <div class="right medium">
                        <%= f.label :admin_approves_spotted %>
                        <%= f.select :admin_approves_spotted, ([['Manual', 1], ['Automática', 0]]), {}, { class: "form-control"} %>
                    </div>
                </div>
                
                <div class="btn-update">
                    <%= f.submit 'Atualizar', class: 'botao' %>
                </div>
            <% end %>

            <%= form_for :user , url: setting_manager_path(college: @college) do |f| %>
                <legend>Adicionar Administrador</legend>
                
                <div class="nickname">
                    <%= f.label 'Nickname do usuário' %>
                    <%= f.text_field :nickname, class:"form-control" %>
                </div>
                <div class="btn-add">
                    <%= f.submit 'Adicionar', class: 'botao' %>                    
                </div>
            <% end %>

            <legend>Lista de administradores</legend>
            
            <div class="admin-list">
                <%= button_to 'Ver lista de administradores', college_administrator_path(@college), method: "get", class: 'botao xlarge' %>
            </div>

            <legend><%= translate 'apagar_pagina' %></legend>

            <div class="btn-delete">
                <%= button_to "Apagar a página", college_path(@college), method: :delete, data: { confirm: "Você tem certeza que quer apagar está página e todo o conteúdo dentro dela? Essa ação não pode ser desfeita." }, id: "delete-button", class: 'botao' %>
            </div>

            <hr>

            <div class="btn-back">
                <%= button_to 'Voltar', favorite_colleges_path, method: "get", class: 'botao small' %>
            </div>
        </div>
    </div>
</div>

src/app/app/views/colleges/index.html.erb
<div class="colleges" id="index">

  <div class="jumbotron">
    <h2>Menu de Faculdades </h2>
    <div class="collegebox">
      <% @colleges.each do |college| %>

        <div class="college" >

          <div class="summary">
            <div class="name"><%= college.initials %> - <%= college.unit %></div>

            <div class="options">
              <% if isPageAdmin(college.id) %>
                <%= link_to "Gerenciar", college_college_whitelists_path(college.id) %>
                <%= link_to "Editar", edit_college_path(college) %>
                <%= link_to image_tag('pink_star.svg', width: "17"), favorite_college_path(college, type: "admin"), method: :put, id: "star-purple" %>
              <% else %>
                <% if already_favorited(college.id) %>
                  <%= link_to image_tag('yellow_star.svg', width: "17"), favorite_college_path(college, type: "unfavorite"), method: :put, id: "star" %>
                <% else %>
                  <%= link_to image_tag('white_star.svg', width: "17"), favorite_college_path(college, type: "favorite"), method: :put, id: "star-white" %>
                <% end %>
              <% end %>
            </div>
          </div>

          <div class="details">
            <div class="specifications">
                <%= college.name %> - <%= college.initials %>
                <br>
                <%= college.unit %>
                <br>
                <%= college.city %> - <%= college.state %>
                <br>
                <%= college.country %>
                <br>
            </div>
          
            <div class="college-btn">
              <% if college.request_to_participate == "0" %>
                <a class="botao small" href="<%= college_spotteds_path(college_id: college.id) %>">Entrar</a>
              <% else %>
                <% if isPageAdmin(college.id) %>
                  <a class="botao small" href="<%= college_spotteds_path(college_id: college.id) %>">Entrar</a>
                <% else %>
                  <a class="botao small" href="<%= college_verify_permission_path(college_id: college.id) %>">Entrar</a>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>

      <%end%>
    </div>

    <div class="btn-create">
      <%= button_to 'Criar nova página', new_college_path, method: "get", class: 'botao large' %>
    </div>
  </div>
</div>

src/app/app/views/colleges/new.html.erb
<div class="colleges" id="new">

    <div class="jumbotron">
        <h2 class="title">Cadastre sua faculdade</h2>

        <div class="form">
            <%= form_for @college do |f| %>
                <%= render 'layouts/error_messages', object: f.object %>

                <div class="box">
                    <div class="left">
                        <%= f.label :name %>
                        <%= f.text_field :name, class: 'form-control' %>
                    </div>
                    <div class="right">
                        <%= f.label :initials %>
                        <%= f.text_field :initials, class: 'form-control' %>
                    </div>
                </div>

                <div class="box">
                    <div class="left">
                        <%= f.label :city %>
                        <%= f.text_field :city, class: 'form-control' %>
                    </div>
                    <div class="right">
                        <%= f.label :state %>
                        <%= f.text_field :state, class: 'form-control' %>
                    </div>
                </div>

                <div class="box">
                    <div class="left">
                        <%= f.label :country %>
                        <%= f.text_field :country, class: 'form-control' %>
                    </div>
                    <div class="right">
                        <%= f.label :unit %>
                        <%= f.text_field :unit, class: 'form-control' %>
                    </div>
                </div>

                <legend><%= translate 'identidade_visual' %></legend>
                
                <div class="box">
                    <div class="left small">
                        <%= f.label :font_color %>
                        <%= f.color_field :font_color, class:"form-control" %>
                    </div>
                    <div class="right big">
                        <%= f.label :font_family %>
                        <%= f.text_field :font_family, class:"form-control" %>
                    </div>
                </div>

                <div class="box">
                    <div class="left small">
                        <%= f.label :background_color %>
                        <%= f.color_field :background_color, class:"form-control" %>
                    </div>
                    <div class="right big">
                        <%= f.label :background_image %>
                        <%= f.text_field :background_image, class:"form-control" %>
                    </div>
                </div>

                <legend><%= translate 'administracao' %></legend>
                
                <div class="box">
                    <div class="left">
                        <%= f.label :request_to_participate %>
                        <%= f.select :request_to_participate, ([['Sim', 1], ['Não', 0]]), {}, { class: "form-control"} %>
                    </div>
                    <div class="right">
                        <%= f.label :admin_approves_spotted %>
                        <%= f.select :admin_approves_spotted, ([['Manual', 1], ['Automática', 0]]), {}, { class: "form-control"} %>
                    </div>
                </div>

                <div class="register">
                    <%= f.submit 'Cadastrar', class: 'botao' %>
                </div>
            <% end %>
        </div>
    </div>

</div>

src/app/app/views/colleges/per_area.html.erb
<div class="colleges" id="per_area">

  <div class="jumbotron">
    <h2 >Páginas de instituições próximas</h2>
    <div class="collegebox">    

      <% @colleges.each do |college| %>
        <div class="college">

          <div class="details">
            <table>
              <thead>
                <tr>
                  <th class="col1"></th>
                  <th class="col2"></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Nome</td>
                  <td><%= college.name %></td>
                </tr>
                <tr>
                  <td>Sigla</td>
                  <td><%= college.initials %></td>
                </tr>
                <tr>
                  <td>Cidade</td>
                  <td><%= college.city %></td>
                </tr>
                <tr>
                  <td>Estado</td>
                  <td><%= college.state %></td>
                </tr>
                <tr>
                  <td>País</td>
                  <td><%= college.country %></td>
                </tr>
                <tr class="noBorder">
                  <td>Unidade</td>
                  <td><%= college.unit %></td>
                </tr>
              </tbody>
            </table>
          </div>
          
          <div class="favorite">
            Favoritar 
            <% if isPageAdmin(college.id) %>
              <%= link_to image_tag('star-purple.png'), favorite_college_path(college, type: "admin"), method: :put, id: "star-purple" %>
            <% else %>
              <% if already_favorited(college.id) %>
                <%= link_to image_tag('star.png'), favorite_college_path(college, type: "unfavorite"), method: :put, id: "star" %>
              <% else %>
                <%= link_to image_tag('star-white.png'), favorite_college_path(college, type: "favorite"), method: :put, id: "star-white" %>
              <% end %>
            <% end %>
          </div>

          <div class="college-btn">
            <%= button_to 'Ver página', college_spotteds_path(college_id: college.id), method: "get", class: "botao small" %>
          </div>

        </div>
      <%end%>

    </div>

    <div class="btn-end">
      <%= button_to 'Finalizar', user_path(current_user), method: "get", class: 'botao small' %>
    </div>

  </div>

</div>

src/app/app/views/colleges/show.html.erb
<h2> Bem-vindo à <%= @college.name %> </h2>