src/app/config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/new'
  get 'static_pages/create'

  get '/about', to:'static_pages#about' 

  resources :contact, only: [:index, :new, :create]

  root to: "welcome#index"

  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'
  get '/users', to: 'users#new'

  get 'favorite_colleges', to: 'favorite_colleges#show'
  get 'favorite_spotteds', to: 'favorite_spotteds#show'
  get 'list_likes', to: 'spotteds#list_likes'
  post 'setting_manager', to: 'administrators#setting_manager'

  get 'per_area', to: 'colleges#per_area'

  resources :users, only: [:new, :create, :show, :edit, :update]
  
  resource :users do
    member do
      post :change_menu_preference
    end
  end

  resources :colleges, only: [:new, :create, :show, :index, :edit, :update] do
    resources :spotteds, only: [:new, :create, :show, :index, :destroy]
    resources :administrators, only: [:show, :destroy]
  end

  resources :colleges, only: [:new, :create, :show, :index, :edit, :update] do
    resources :college_whitelists
  end

  resources :colleges do
    put :favorite, on: :member
  end

  resources :spotteds, only: [:new, :create, :show, :index, :delete] do
    resources :comments
  end

  resources :colleges, only: [:new, :create, :show, :index, :edit, :update] do
    resources :college_whitelists, only: [:new, :create, :index, :update]
    get 'verify_permission', to: 'college_whitelists#verify_permission'
  end
  
  resources :spotteds, only: [:new, :create, :show, :index] do
    resources :likes
  end

  resources :spotteds do
    put :favorite, on: :member
  end

end

src/app/app/models/spotted.rb
class Spotted < ApplicationRecord
    validates :image, presence: false
    validates :content, presence: true, length: {minimum: 1}    

    belongs_to :college
    belongs_to :user
    has_many :like, dependent: :destroy
    has_many :comment, dependent: :destroy
    has_many :favorite_spotteds, dependent: :destroy
    has_many :favorited_by, through: :favorite_spotteds, source: :user, dependent: :destroy
end

src/app/app/controllers/spotteds_controller.rb
class SpottedsController < ApplicationController
    before_action :set_college, only: [:index, :new]
    before_action :set_font_google, only: [:index, :new]
    before_action :set_style, only: [:index, :new]
    
    def index
        @spotteds = @college.spotteds
    end

    def new
        @spotted = Spotted.new
        @spotted.user = current_user
    end

    def show
        @spotted = Spotted.find(params[:id])
        @comments = @spotted.comment.all
    end

    def create
        @spotted = Spotted.new(spotted_params)
        @spotted.user = current_user
        @spotted.college = College.find(params[:college_id])
        @spotted.college_spotted_counter = Spotted.where(college_id: @spotted.college_id).count + 1
        
        if (spotted_params[:image])
            img_file = spotted_params[:image].tempfile.open.read.force_encoding(Encoding::UTF_8)
            @spotted.image = Base64.encode64(img_file)
        end

        if @spotted.save
            flash[:sucess] = 'Spotted cadastrado com sucesso'
            redirect_to college_spotteds_path
        else
            render 'new'
        end
    end

    def list_likes
        @spotted = Spotted.find(params[:spotted_id])
        respond_to do |format|
            format.html
            format.js
        end
    end

    def destroy
        @spotted = Spotted.find(params[:id])  
        @spotted.destroy
        flash[:success] = 'Spotted apagado com sucesso'
        redirect_to college_spotteds_path(@spotted.college)
    end

    def favorite
        @spotted = Spotted.find(params[:id])
        type = params[:type]
        if type == "favorite"
            current_user.notification << @spotted
            notice = "Você favoritou esse spotted com sucesso"
            flash[:success] = notice
            redirect_back fallback_location: college_spotteds_path(@spotted.college)

        elsif type == "unfavorite"
            current_user.notification.delete(@spotted)
            notice = "Você desfavoritou esse spotted com sucesso"
            flash[:success] = notice
            redirect_back fallback_location: college_spotteds_path(@spotted.college)
        end
        
    end

    private 
        def spotted_params
            params.require(:spotted).permit(:content, :image)
        end

        def set_user_creator
            user = User.find_by(email: params[:session][:email].downcase)
        end

        def set_college
            @college = College.find(params[:college_id])
        end

        def set_style
            @college_style = ''
            check_to_set_background_image
            check_to_set_background_color
            check_to_set_font_family_and_color
        end

        def check_to_set_background_image
            if @college.background_image.present?
                @college_style.concat('body { background-image: url(' + @college.background_image + '); }')
            end
        end

        def check_to_set_background_color
            if @college.background_color.present?
                @college_style.concat('body { background-color:' + @college.background_color + ';}')
            end
        end

        def check_to_set_font_family_and_color
            if @college.font_family.present? && @college.font_color.present?
                @college_style.concat('#content-container { font-family: ' + @college.font_family + '!important; color: ' + @college.font_color + '; }')
            elsif @college.font_family.present?
                @college_style.concat('#content-container { font-family: ' + @college.font_family + '!important; }')
            elsif @college.font_color.present?
                @college_style.concat('#content-container { color: ' + @college.font_color + '; }')
            end
        end


        def set_font_google
            response = HTTParty.get('https://fonts.googleapis.com/css?family=' + @college.font_family)

            if response.code == 200 || response.code == "200"
                @font_google_link = "https://fonts.googleapis.com/css?family=" + @college.font_family
            end
        end
end

src/app/app/helpers/spotteds_helper.rb
module SpottedsHelper
end

src/app/app/views/spotteds/_list_comments.html.erb
<div id="list-comment">

    <% @comments.each do |comment| %>
        <div class="comment-container">
            <% if current_user.id == comment.user.id %> 
                <% if comment.user.profile_picture? %> 
                    <img src="data:image;base64,<%= comment.user.profile_picture %>" class="img-responsive" style="width: 40px; height: 40px; float: left; border-radius: 50px; margin-right: 5px;" alt="Profile picture">
                <% else %>
                    <%= image_tag 'default_profile_picture.png', alt: 'Profile picture', class: 'img-responsive', style: "width: 40px; height: 40px; float: left; margin-right: 5px;" %>
                <% end %>
                <div class="dropdown">
                    <label>
                        <%= comment.user.first_name + ' ' + comment.user.last_name %>
                    </label>
                    <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <%= link_to spotted_comment_path(@spotted, comment), method: :delete, data: { confirm: "Você tem certeza que deseja apagar este comentário? Essa ação não pode ser desfeita." }, id: "trash-bt" do %>
                                <i class="fa fa-trash fa-lg"  style="color:black"></i>
                                Apagar comentário
                            <% end %>
                        </li>
                        <li>
                            <%= link_to "#", method: :get do %>
                                <i class="fa fa-pencil fa-lg"  style="color:black"></i>
                                Editar comentário
                            <% end %>
                        </li>
                    </ul>
                </div>
            <% else %>
                <% if comment.user.profile_picture? %> 
                    <img src="data:image;base64,<%= comment.user.profile_picture %>" class="img-responsive" style="width: 40px; height: 40px; float: left; border-radius: 50px; margin-right: 5px;" alt="Profile picture">
                <% else %>
                    <%= image_tag 'default_profile_picture.png', alt: 'Profile picture', class: 'img-responsive', style: "width: 40px; height: 40px; float: left; margin-right: 5px;" %>
                <% end %>
                <label>
                    <%= comment.user.first_name + ' ' + comment.user.last_name %>
                </label>
            <% end %>   

            <div class="comentario">
                <p><%= comment.content %></p>
            </div>
        </div>
    <% end %>

</div>

src/app/app/views/spotteds/_list_users_likes.html.erb
<div class="modal-header">

  <button type="button" class="close" data-dismiss="modal">x</button>

  <h4 class="modal-title" id="myModalLabel">Curtidas</h4>

</div>

<div class="modal-body">

  <% @spotted.like.each do |like| %>
    <p> <%= like.user.nickname %> </p>
  <%end%>

</div>

src/app/app/views/spotteds/_new_comments.html.erb
<div id="new-comment">
    <%= form_for([@spotted, @spotted.comment.build]) do |f| %>
        <%= render 'layouts/error_messages', object: f.object %>
        <div class="form-group" id="comment-area">

            <div class="new-comment-text">
                <%= f.text_field :content, class: 'form-control' %>
            </div>

            <div class="send-button">
                <%= button_tag type: 'submit', class: 'btn', id: 'send-comment-button' do %>
                    <i class="fa fa-paper-plane"></i>
                <% end %>
            </div>

        </div>
    <% end %>
</div>

src/app/app/views/spotteds/index.html.erb
<% content_for :for_head do %>
    <style>
        <%= @college_style %>
    </style>
    <link href="<%= @font_google_link %>" rel='stylesheet'>
<% end %>

<div class="spotteds" id="index">

    <h2 class="title"><%= @college.name %>

        <% if isPageAdmin(@college.id) %>
            <td style="text-align: center"><%= link_to image_tag('pink_star.svg'), favorite_college_path(@college, type: "admin"), method: :put, id: "star-purple" %></td>
        <% else %>
            <% if already_favorited(@college.id) %>
                <td style="text-align: center"><%= link_to image_tag('yellow_star.svg'), favorite_college_path(@college, type: "unfavorite"), method: :put, id: "star" %></td>
            <% else %>
                <td style="text-align: center"><%= link_to image_tag('white_star.svg'), favorite_college_path(@college, type: "favorite"), method: :put, id: "star-white" %></td>
            <% end %>
        <% end %>

    </h2>

    <div class="container-area">

        <div class="container-left"> 
            <div class="details">
                <table>
                    <thead>
                        <tr>
                            <th class="col1"></th>
                            <th class="col2"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Nome</td>
                            <td><%= @college.name %></td>
                        </tr>
                        <tr>
                            <td>Sigla</td>
                            <td><%= @college.initials %></td>
                        </tr>
                        <tr>
                            <td>Cidade</td>
                            <td><%= @college.city %></td>
                        </tr>
                        <tr>
                            <td>Estado</td>
                            <td><%= @college.state %></td>
                        </tr>
                        <tr>
                            <td>País</td>
                            <td><%= @college.country %></td>
                        </tr>
                        <tr>
                            <td>Unidade</td>
                            <td><%= @college.unit %></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="botoes">
                <br>
                <%= button_to 'Novo spotted', new_college_spotted_path, method: "get", action: "create", class: 'botao' %>

                <% if isPageAdmin(@college.id) %>
                    <%= button_to "Editar", edit_college_path(@college.id), method: "get", action: "edit", class: 'botao', id: "editar-button" %>
                <% end %>

                <%= button_to 'Voltar', colleges_path, method: "get", class: 'botao' %>
            </div>
        </div>

        <div class="panel panel-default">
            <% @spotteds.reverse_each do |spotted| %>
                <div class="panel-body">
                    <div class="drop2">
                        <div class="dropdown">
                            <a class="dropdown-toggle2" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <span class="caret"></span>
                            </a>
                            <% if already_favorited_spotted(spotted.id) %>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li>
                                        <%= link_to favorite_spotted_path(spotted, type: "unfavorite"), method: :put, id: "desativar-not"  do %>
                                            Desativar notificações 
                                        <% end %>
                                    </li>
                                </ul>
                            <% else %>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li>
                                        <%= link_to favorite_spotted_path(spotted, type: "favorite"), method: :put, id: "ativar-not"  do %>
                                            Ativar notificações
                                        <% end %>
                                    </li>
                                </ul>
                        <% end %>
                    </div>
                </div>
                    <div class="spotted-content">
                        <div class="spotted-number">
                            <%= link_to college_spotted_path(:college_id, spotted.id) do %>
                                Spotted <%= spotted.college_spotted_counter %>
                            <% end %>
                        </div> 
                        <div class="spotted-text">
                            <%= simple_format(spotted.content) %>
                        </div>
                        <% pre_like = spotted.like.find { |like| like.user_id == current_user.id} %>
                        <% like_count = spotted.like.count %>
                        <p>
                            <% link = '' %>
                            <% if pre_like %>
                                <% link = (like_count) == 1 ? 'Você curtiu' : (like_count - 1) < 2 ? 'Você e mais ' + (like_count - 1).to_s + ' pessoa curtiu' : 'Você e mais ' + (like_count - 1).to_s + ' pessoas curtiram' %>
                            <% else %>
                                <%if like_count >= 1 %>
                                    <% link = (like_count) == 1 ? 'Uma pessoa curtiu' : like_count.to_s + ' pessoas curtiram' %>
                                <% else %>
                                <% end %>
                            <% end %>
                            <%= link_to link, list_likes_path(spotted_id: spotted.id), {:remote => true, 'data-toggle' => "modal", 'data-target' => "#modal-window"}%>
                        </p>
                    </div>
                    <div class="spotted-options">
                        <div class="thumbs">
                            <% if pre_like %> 
                                <%= link_to spotted_like_path(spotted, pre_like), method: :delete do %>
                                    <i class="fa fa-thumbs-up fa-2x"  style="color:black"></i> 
                                <% end %>
                            <% else %>
                                <%= link_to spotted_likes_path(spotted), method: :post do %>
                                    <i class="fa fa-thumbs-o-up fa-2x"  style="color:black"></i> 
                                <% end %>
                            <% end %>
                        </div>
                        <div class="trash">
                            <% if isPageAdmin(@college.id) %> 
                                <%= link_to college_spotted_path(:college_id, spotted.id), method: :delete, data: { confirm: "Você tem certeza que deseja apagar este spotted? Essa ação não pode ser desfeita." }, id: "trash-bt" do %>
                                    <i class="fa fa-trash fa-2x"  style="color:black"></i> 
                                <% end %>
                            <% end %>
                        </div>
                        <div id="modal-window" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content"></div>
                            </div>
                        </div>
                        <%= button_to 'Ver spotted', college_spotted_path(:college_id, spotted.id), method: "get", class: 'botao small' %>
                    </div>
                </div>
            <% end %>
        </div>

        <div id="clear"></div>

    </div>
</div>

src/app/app/views/spotteds/list_likes.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'list_users_likes') %>");
$("#modal-window").modal();

src/app/app/views/spotteds/new.html.erb
<% content_for :for_head do %>
    <style>
        <%= @college_style %>
    </style>
    <link href="<%= @font_google_link %>" rel='stylesheet'>
<% end %>

<div class="spotteds" id="new">

    <h2 class="title">Novo spotted</h2>

    <div class="spotted-content">
        <%= form_for(@spotted, url: college_spotteds_path) do |f| %>
            <%= render 'layouts/error_messages', object: f.object %>
            <div class=form-group>
                <%= f.label :content %>
                <%= f.text_area :content, class: 'form-control', id: 'text-area', placeholder: 'Escreva o seu spotted aqui' %>
                <%= f.file_field :image, class: 'form-control' %>
            </div>
            <%= f.submit 'Mandar spotted', class: 'botao' %>
        <% end %>
        <p>
            <%= button_to 'Voltar', college_spotteds_path, method: "get", class: 'botao' %>
        </p>
    </div>

</div>

src/app/app/views/spotteds/show.html.erb
<h2>Spotted n. <%= @spotted.college_spotted_counter %></h2>
<p><%= button_to 'Voltar', college_spotteds_path(@spotted.college.id), method: "get", class: 'botao small' %></p>

<div class="panel panel-default" id="show">

    <div class="container-left">
        <div class="panel-body">
            <%= simple_format(@spotted.content) %>
            <% if @spotted.image? %>
                <p><img src="data:image;base64,<%= @spotted.image %>" id="image" class="img-responsive" style="width: 100%; height: auto;"></p>
            <% end %>
        </div>
    </div>

    <div class="container-right">
        <div class="row">
            <% like_count = @spotted.like.count %>
            <% pre_like = @spotted.like.find { |like| like.user_id == current_user.id} %>
            <p class="curtida">
                <% link = '' %>
                <% if pre_like %>
                    <% link = (like_count) == 1 ? 'Você curtiu' : (like_count - 1) < 2 ? 'Você e mais ' + (like_count - 1).to_s + ' pessoa curtiu' : 'Você e mais ' + (like_count - 1).to_s + ' pessoas curtiram' %>
                <% else %>
                    <%if like_count >= 1 %>
                        <% link = (like_count) == 1 ? 'Uma pessoa curtiu' : like_count.to_s + ' pessoas curtiram' %>
                    <% else %>
                    <% end %>
                <% end %>
                <%= link_to link, list_likes_path(spotted_id: @spotted.id), {:remote => true, 'data-toggle' => "modal", 'data-target' => "#modal-window"}%>
            </p>
        </div>
        <div id="modal-window" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content"></div>
            </div>
        </div>
        <div class='row' id="curtir-e-comentar">
            <div class="mao">
                <% if pre_like %>
                    <%= link_to spotted_like_path(@spotted, pre_like, :origin => 'modal'), method: :delete do %>
                        <i class="fa fa-thumbs-up fa-2x"  style="color:black"></i> 
                    <% end %>
                <% else %>
                    <%= link_to spotted_likes_path(@spotted, :origin => 'modal'), method: :post do %>
                        <i class="fa fa-thumbs-o-up fa-2x"  style="color:black"></i> 
                    <% end %>
                <% end %>        
            </div>
            <div class="comment">
                <%= render 'spotteds/new_comments' %>
            </div>
        </div>
        <div class="scroll">
            <div class="row col-md-12 col-sm-12">
                <%= render 'spotteds/list_comments' %>
            </div>
        </div>
    </div>

    <div id="clear"></div>

</div>