src/app/config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/new'
  get 'static_pages/create'

  get '/about', to:'static_pages#about' 

  resources :contact, only: [:index, :new, :create]

  root to: "welcome#index"

  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'
  get '/users', to: 'users#new'

  get 'favorite_colleges', to: 'favorite_colleges#show'
  get 'favorite_spotteds', to: 'favorite_spotteds#show'
  get 'list_likes', to: 'spotteds#list_likes'
  post 'setting_manager', to: 'administrators#setting_manager'

  get 'per_area', to: 'colleges#per_area'

  resources :users, only: [:new, :create, :show, :edit, :update]
  
  resource :users do
    member do
      post :change_menu_preference
    end
  end

  resources :colleges, only: [:new, :create, :show, :index, :edit, :update] do
    resources :spotteds, only: [:new, :create, :show, :index, :destroy]
    resources :administrators, only: [:show, :destroy]
  end

  resources :colleges, only: [:new, :create, :show, :index, :edit, :update] do
    resources :college_whitelists
  end

  resources :colleges do
    put :favorite, on: :member
  end

  resources :spotteds, only: [:new, :create, :show, :index, :delete] do
    resources :comments
  end

  resources :colleges, only: [:new, :create, :show, :index, :edit, :update] do
    resources :college_whitelists, only: [:new, :create, :index, :update]
    get 'verify_permission', to: 'college_whitelists#verify_permission'
  end
  
  resources :spotteds, only: [:new, :create, :show, :index] do
    resources :likes
  end

  resources :spotteds do
    put :favorite, on: :member
  end

end

src/app/app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

    validates :email, presence: true, length: {maximum: 255}, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: true }
    validates :nickname, presence: true, length: {maximum: 30}, uniqueness: { case_sensitive: true }
    validates :first_name, presence: true, length: {maximum: 50}
    validates :last_name, presence: true, length: {maximum: 50}
    validates :password, presence: true, length: {minimum: 6}
    validates :password_confirmation, presence: true, length: {minimum: 6}
    validates :birth_date, presence: true
    validates :city, presence: true
    validates :state, presence: true, length: {maximum: 2, minimum: 2}
    validates :country, presence: true
    validate :profile_picture_content_type

    has_many :spotted
    has_many :college
    has_many :like, dependent: :destroy
    has_many :comment, dependent: :destroy
    has_many :favorite_colleges
    has_many :favorites, through: :favorite_colleges, source: :college
    has_many :administrator
    has_many :college_whitelist
    has_many :favorite_spotteds
    has_many :notification, through: :favorite_spotteds, source: :spotted

    def profile_picture_content_type
        if self[:profile_picture_content_type]
            unless self[:profile_picture_content_type] == "image/jpeg" || self[:profile_picture_content_type] == "image/png"
                errors.add(:profile_picture_content_type, "deve ser no formato JPEG ou PNG")
            end
        end
    end

end

src/app/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_logged_in_user, only: [:edit, :update]
    
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)

        if (user_params[:profile_picture])
            img_file = user_params[:profile_picture].tempfile.open.read.force_encoding(Encoding::UTF_8)
            img_file_type = user_params[:profile_picture].content_type
            @user.profile_picture = Base64.encode64(img_file)
            @user.profile_picture_content_type = img_file_type
        end

        if @user.save
            if params[:see_fav_pages]
                sign_in(@user)

                redirect_to per_area_path
            else 
                flash[:success] = 'Usuário cadastrado com sucesso'
                redirect_to root_url
            end
        else
            render 'new'
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])

        if params[:user][:profile_picture]
            img_file = params[:user][:profile_picture].tempfile.open.read.force_encoding(Encoding::UTF_8)
            img_file_type = params[:user][:profile_picture].content_type
            params[:user][:profile_picture] = Base64.encode64(img_file)
            params[:user][:profile_picture_content_type] = img_file_type
        elsif @user.profile_picture
            params[:user][:profile_picture] = @user.profile_picture
            params[:user][:profile_picture_content_type] = @user.profile_picture_content_type
        end

        if @user.update(user_params)
            flash[:success] = 'Dados atualizados.'
            sign_in @user
            redirect_to user_path(@user)
        else
            render 'edit'
        end
    end

    def change_menu_preference
        type = params[:type]
        if type == "circle"
            current_user.update_column(:menu_preference, "circle")
            redirect_back fallback_location: root_url

        elsif type == "list"
            current_user.update_column(:menu_preference, "list")
            redirect_back fallback_location: root_url

        else
            redirect_back fallback_location: root_url, notice: 'Nada aconteceu.'
        end
      end

    private
        def user_params
            params.require(:user).permit(:email, :nickname, :first_name, :last_name, :password, :password_confirmation, :birth_date, :city, :state, :country, :profile_picture, :profile_picture_content_type)
        end
end

src/app/app/helpers/users_helper.rb
module UsersHelper
end

src/app/app/views/users/edit.html.erb
<div class="user" id="edit">

    <div class="jumbotron">
        <h2 class="title">Alterar dados</h2>
        <div class="profile-picture">
            <% if current_user.profile_picture? %>
                <img src="data:image;base64,<%= current_user.profile_picture %>" class="img-responsive" alt="Profile picture">
            <% else %>
                <%= image_tag 'default_profile_picture.png', alt: 'Profile picture', class: 'img-responsive', style: "width: 40px; height: 40px; float: left;" %>
            <% end %>  
        </div>

        <div class="data">
            <%= form_for(@user) do |f| %>

                <%= render 'layouts/error_messages', object: f.object %>

                <div class="picture">
                    <%= f.label :profile_picture do %>
                        <i class="fa fa-upload fa-2x" aria-hidden="true"></i> Alterar imagem de perfil
                    <% end %>
                    <%= f.file_field :profile_picture, class: 'form-control', accept: 'image/jpeg, image/png' %>
                </div>

                <div class="file">Nenhum arquivo selecionado.</div>

                <hr>

                <div class="box">
                    <div class="left">
                        <%= f.label :first_name %>
                        <%= f.text_field :first_name, class:'form-control' %>
                    </div>

                    <div class="right">
                        <%= f.label :last_name %>
                        <%= f.text_field :last_name, class:'form-control' %>
                    </div>
                </div>

                <div class="box">
                    <div class="left">
                        <%= f.label :nickname %>
                        <%= f.text_field :nickname, class:'form-control' %>
                    </div>

                    <div class="right">
                        <%= f.label :birth_date %>
                        <%= f.date_field :birth_date, class:'form-control' %>
                    </div>
                </div>

                <div class="email">
                    <%= f.label :email %>
                    <%= f.text_field :email, class:'form-control' %>
                </div>

                <hr>

                <div class="box">
                    <div class="left">
                        <%= f.label :password %>
                        <%= f.password_field :password, class:'form-control' %>
                    </div>

                    <div class="right">
                        <%= f.label :password_confirmation %>
                        <%= f.password_field :password_confirmation, class:'form-control' %>
                    </div>
                </div>
                
                <hr>
                
                <div class="box">
                    <div class="left">
                        <%= f.label :country %>
                        <%= f.text_field :country, class:'form-control' %>
                    </div>

                    <div class="right">
                        <%= f.label :state %>
                        <%= f.text_field :state, class:'form-control' %>
                    </div>
                </div>

                <div class="city">
                    <%= f.label :city %>
                    <%= f.text_field :city, class:'form-control' %>
                </div>
                
                <hr>

                <div class="save">
                    <%= f.submit "Salvar", class: "botao" %>
                </div>

            <% end %>
        </div>
    </div>

</div>

src/app/app/views/users/new.html.erb
<div class="user" id="new">

    <div class="jumbotron">
        <div class="register-area">
            <div class="form">
                <h2>Cadastre-se</h1>
                <%= form_for @user do |f| %>

                    <%= render 'layouts/error_messages', object: f.object %>

                    <div class="box">
                        <div class="left">
                            <%= f.label :first_name %>
                            <%= f.text_field :first_name, class: 'form-control' %>
                        </div>
                        <div class="right">
                            <%= f.label :last_name %>
                            <%= f.text_field :last_name, class: 'form-control' %>
                        </div>
                    </div>

                    <div class="box">
                        <div class="left">
                            <%= f.label :nickname %>
                            <%= f.text_field :nickname, class: 'form-control' %>
                        </div>
                        <div class="right">
                            <%= f.label :birth_date %>
                            <%= f.date_field :birth_date, class:'form-control' %>
                        </div>
                    </div>

                    <div class="email">
                        <%= f.label :email %>
                        <%= f.text_field :email, class: 'form-control' %>  
                    </div>

                    <hr>

                    <div class="box">
                        <div class="left">
                            <%= f.label :password %>
                            <%= f.password_field :password, class: 'form-control' %>
                        </div>

                        <div class="right">
                            <%= f.label :password_confirmation %>
                            <%= f.password_field :password_confirmation, class: 'form-control' %>
                        </div>
                    </div>

                    <hr>

                    <div class="box">
                        <div class="left">
                            <%= f.label :country %>
                            <%= f.text_field :country, class: 'form-control' %>
                        </div>
                        
                        <div class="right">
                            <%= f.label :state %>
                            <%= f.text_field :state, class: 'form-control' %>
                        </div>
                    </div>

                    <div class="city">
                        <%= f.label :city %>
                        <%= f.text_field :city, class: 'form-control' %>
                    </div>

                    <hr>

                    <div class="profile-picture">
                        <%= f.label :profile_picture %>
                        <%= f.file_field :profile_picture, class: 'form-control', accept: 'image/jpeg, image/png' %>
                    </div>

                    <hr>

                    <div class="fav-pages" id="div-see-fav-pages">
                        <%= check_box_tag :see_fav_pages, 1, false, id: "checkbox" %>
                        <label class="form-check-label" for="see_fav_pages">Desejo ver as páginas recomendadas para mim</label>
                    </div>

                    <div class="register">
                        <%= f.submit 'Cadastrar', class: 'botao' %>
                    </div>

                    <script>
                        var latitude = null;
                        var longitude = null;
                        var cidade = null;
                        var estado = null;
                        var pais = null;
                        var estados_brasil = [
                            {
                                estado_sigla: 'AC',
                                estado: 'Acre'
                            },
                            {
                                estado_sigla: 'AL',
                                estado: 'Alagoas'
                            },
                            {
                                estado_sigla: 'AP',
                                estado: 'Amapá'
                            },
                            {
                                estado_sigla: 'AM',
                                estado: 'Amazonas'
                            },
                            {
                                estado_sigla: 'BA',
                                estado: 'Bahia'
                            },
                            {
                                estado_sigla: 'CE',
                                estado: 'Ceará'
                            },
                            {
                                estado_sigla: 'DF',
                                estado: 'Distrito Federal'
                            },
                            {
                                estado_sigla: 'ES',
                                estado: 'Espírito Santo'
                            },
                            {
                                estado_sigla: 'GO',
                                estado: 'Goiás'
                            },
                            {
                                estado_sigla: 'MA',
                                estado: 'Maranhão'
                            },
                            {
                                estado_sigla: 'MT',
                                estado: 'Mato Grosso'
                            },
                            {
                                estado_sigla: 'MS',
                                estado: 'Mato Grosso do Sul'
                            },
                            {
                                estado_sigla: 'MG',
                                estado: 'Minas Gerais'
                            },
                            {
                                estado_sigla: 'PA',
                                estado: 'Pará'
                            },
                            {
                                estado_sigla: 'PB',
                                estado: 'Paraíba'
                            },
                            {
                                estado_sigla: 'PR',
                                estado: 'Paraná'
                            },
                            {
                                estado_sigla: 'PE',
                                estado: 'Pernambuco'
                            },
                            {
                                estado_sigla: 'PI',
                                estado: 'Piauí'
                            },
                            {
                                estado_sigla: 'RJ',
                                estado: 'Rio de Janeiro'
                            },
                            {
                                estado_sigla: 'RN',
                                estado: 'Rio Grande do Norte'
                            },
                            {
                                estado_sigla: 'RS',
                                estado: 'Rio Grande do Sul'
                            },
                            {
                                estado_sigla: 'RO',
                                estado: 'Rondônia'
                            },
                            {
                                estado_sigla: 'RR',
                                estado: 'Roraima'
                            },
                            {
                                estado_sigla: 'SC',
                                estado: 'Santa Catarina'
                            },
                            {
                                estado_sigla: 'SP',
                                estado: 'São Paulo'
                            },
                            {
                                estado_sigla: 'SE',
                                estado: 'Sergipe'
                            },
                            {
                                estado_sigla: 'TO',
                                estado: 'Tocantins'
                            }
                        ];

                        var geolocationPromise = new Promise(function(resolve, reject){
                            if(navigator.geolocation){
                                navigator.geolocation.getCurrentPosition(function (position) {
                                    latitude = position.coords.latitude;
                                    longitude = position.coords.longitude;

                                    resolve();
                                });
                            }		
                            else {
                                resolve();
                            }
                        });
                        geolocationPromise.then(function(){
                            var addressPromise = new Promise (function(resolve, reject) {
                                var endereco = (latitude != null && latitude != undefined && latitude != ""  ? (latitude + '-') : '')
                                        + (longitude != null && longitude != undefined && longitude != ""  ? (longitude + '-') : '');

                                var dados = $.ajax({
                                    url: "https://nominatim.openstreetmap.org/reverse/?format=json&lat=" + latitude +"&lon=" +longitude,
                                    type: 'GET',
                                    dataType: 'json',
                                    contentType: 'aplication/json'
                                });
                                dados.done(function () {
                                    cidade = dados.responseJSON.address.city;
                                    estado = dados.responseJSON.address.state;
                                    pais = dados.responseJSON.address.country;
                                    resolve();
                                });
                                dados.fail(function() {
                                    console.log("teste") // TODO
                                });
                            });
                            addressPromise.then(function(){
                                if (pais) {
                                    $("#user_country").val(pais);
                                }
                                if (estado) {
                                    var estado_tratado = estados_brasil.find(function (el) {
                                        return el.estado == estado;
                                    });

                                    if (estado_tratado && estado_tratado.estado_sigla) {
                                        estado = estado_tratado.estado_sigla;
                                    }
                                    else {
                                        var estado_split = estado.split(" ");

                                        if (estado_split.length > 1) {
                                            estado = estado_split[0].substring(0,1) + estado_split[estado_split.length - 1].substring(0,1);
                                        }
                                        else {
                                            estado = estado_split[0].substring(0,1);
                                        }
                                    }

                                    $("#user_state").val(estado);
                                }
                                if (cidade) {
                                    $("#user_city").val(cidade);
                                }
                            });
                        });
                    </script>

                <% end %>
                
            </div>
        </div>
    </div>

</div>

src/app/app/views/users/show.html.erb
<div class="user" id="show">

    <div class="jumbotron">
        <div class="user-area">

            <div class="big-screen">
                <% if current_user.menu_preference == "list" %>
                    <div id="list-menu">
                        <h2>Olá <%= current_user.first_name %></h2>

                        <div class="mybtn">
                            <%= button_to 'Meu perfil', edit_user_path, method: "get", class: 'botao large' %>
                        </div>
                        
                        <div class="mybtn">
                            <%= button_to 'Menu das faculdades', colleges_path, method: "get", action: "show", class: 'botao large', id: 'pages-menu-access' %>
                        </div>

                        <div class="mybtn">
                            <%= button_to 'Faculdades favoritas', favorite_colleges_path, method: "get", action: "show", class: 'botao large' %>
                        </div>

                        <div class="mybtn">
                            <%= button_to 'Amigos', entrar_path, method: "get", class: 'botao large' %>
                        </div>

                        <div class="mybtn">
                            <%= button_to 'Conversas', entrar_path, method: "get", class: 'botao large' %>
                        </div>
                    </div>

                <% elsif current_user.menu_preference == "circle" %>
                    <div id="circle-menu">
                        <div class="profile">
                            <%= button_to edit_user_path, method: "get", class: 'botao circle' do %>
                                <i class="fa fa-id-card" id="icon"></i>
                            <% end %>
                            <span class="tooltiptext">Meu Perfil</span>
                        </div>

                        <div class="second">
                            <div class="menu">
                                <%= button_to colleges_path, method: "get", action: "show", class: 'botao circle', id: 'pages-menu-access' do %>
                                    <i class="fa fa-list-ul" id="icon"></i>
                                <% end %>
                            <span class="tooltiptext">Menu de Faculdades</span>
                            </div>

                            <h2 class="hello">Olá <%= current_user.first_name %></h2>

                            <div class="friends">
                                <%= button_to entrar_path, method: "get", class: 'botao circle' do %>
                                    <i class="fa fa-users" id="icon"></i>
                                <% end %>
                            <span class="tooltiptext">Amigos</span>
                            </div>
                        </div>

                        <div class="third">
                            <div class="favorites">
                                <%= button_to favorite_colleges_path, method: "get", action: "show", class: 'botao circle' do %>
                                    <i class="fa fa-star" id="icon"></i>
                                <% end %>
                            <span class="tooltiptext">Faculdades Favoritas</span>
                            </div>

                            <div class="space"></div>

                            <div class="chat">
                                <%= button_to entrar_path, method: "get", class: 'botao circle' do %>
                                    <i class="fa fa-paper-plane" id="icon"></i>
                                <% end %>
                            <span class="tooltiptext">Conversas</span>
                            </div>
                        </div>
                    </div>
                <% end %>

                <div class="change">
                    <% if current_user.menu_preference == "list" %>
                        <%= button_to "Alterar Menu", change_menu_preference_users_path(type: "circle"), method: "post", action: "change_menu_preference", class: 'botao small black', id: "btn-change-user-menu" %>
                    <% elsif current_user.menu_preference == "circle" %>
                        <%= button_to "Alterar Menu", change_menu_preference_users_path(type: "list"), method: "post", action: "change_menu_preference", class: 'botao small black', id: "btn-change-user-menu" %>
                    <% end %>
                </div>
            </div>

            <div class="small-screen">
                <div id="list-menu">
                    <h2>Olá <%= current_user.first_name %></h2>

                    <div class="mybtn">
                        <%= button_to 'Meu perfil', edit_user_path, method: "get", class: 'botao large' %>
                    </div>
                    
                    <div class="mybtn">
                        <%= button_to 'Menu das faculdades', colleges_path, method: "get", action: "show", class: 'botao large', id: 'pages-menu-access' %>
                    </div>

                    <div class="mybtn">
                        <%= button_to 'Faculdades favoritas', favorite_colleges_path, method: "get", action: "show", class: 'botao large' %>
                    </div>

                    <div class="mybtn">
                        <%= button_to 'Amigos', entrar_path, method: "get", class: 'botao large' %>
                    </div>

                    <div class="mybtn">
                        <%= button_to 'Conversas', entrar_path, method: "get", class: 'botao large' %>
                    </div>
                </div>
            </div>

        </div>
    </div>
    
</div>